---
swagger: "2.0"
info:
  description: "Esta API servirá de backend pro site do MIMV (nome provisório) e o\
    \ APP Android"
  version: "0.1.0"
  title: "Meus Investimentos - IAPP"
  contact:
    email: "rafa@rafacla.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.rafacla.com"
basePath: "/"
tags:
  - name: "adm"
    description: "Permite alterar configurações do servidor e ações com usuários"
  - name: "users"
    description: "Permite criar e editar usuarios"
  - name: "cliente"
    description: "Transações com cliente"
  - name: "diários"
    description: "Lista os diários de um usuário"
  - name: "categorias"
    description: "Permite adicionar ou remover categorias de transações"
  - name: "transações"
    description: "Permite listar, adicionar ou remover transações"
  - name: "orçamentos"
    description: "Permite listar, adicionar ou remover orçamentos mensais"
  - name: "contas"
    description: "Permite listar, adicionar ou remover contas bancárias (e cartões)"
schemes:
  - "https"
security:
  - application:
    - "user"
paths:
  /activate/{actcode}:
    get:
      tags:
      - "users"
      summary: "Ativa um usuário dado o código de ativação"
      parameters:
      - name: "actcode"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK. Usuário ativado"
        401:
          description: "Usuário não autorizado ou código inválido"
  /users/logged:
    get:
      tags:
      - "users"
      summary: "Retorna os detalhes do usuário logado"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              userID:
                type: "number"
              userEmail:
                type: "string"
              userPassword:
                type: "string"
              userFirstName:
                type: "string"
              userLastName:
                type: "string"
              userPhoneNumber:
                type: "string"
              userLastLoginIP:
                type: "string"
              userLastLoginDate:
                type: "string"
              userActivationCode:
                type: "string"
              userForgottenPasswordCode:
                type: "string"
              userForgottenPasswordTime:
                type: "string"
              userActive:
                type: "boolean"
              userNotActiveReason:
                type: "string"
        403:
          description: "Não autorizado"
        500:
          description: "erro do servidor ao buscar usuário"
  /users:
    get:
      tags:
      - "users"
      - "adm"
      summary: "Lista os usuários cadastrados no sistema"
      description: "Lista todos os usuários cadastrados no sistema, retornando seus\
        \ IDs e informações pessoais"
      parameters: []
      responses:
        200:
          description: "OK"
        403:
          description: "Acesso negado: usuário não possui privilégios de administrador"
      security:
      - application:
        - "adm"
    post:
      tags:
      - "users"
      summary: "Cria um novo usuário"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        201:
          description: "Novo usuário criado com sucesso"
          schema:
            type: "object"
            properties:
              status:
                type: "boolean"
                description: "Retorna true se for sucesso"
              id:
                type: "integer"
                description: "Retorna o ID do novo usuário."
        400:
          description: "retorna false para os campos inválidos"
          schema:
            type: "object"
            properties:
              status:
                type: "boolean"
                example: false
                description: "retorna false se falhar"
              reason:
                type: "string"
                example: "usuario_existente"
                description: "retorna usuario_existente ou erro_desconhecido"
  /users/put:
    post:
      tags:
      - "users"
      summary: "Altera um usuário"
      parameters:
      - in: "body"
        name: "body"
        properties:
              id:
                type: "integer"
                description: "Retorna o ID do usuário autenticado."
      responses:
        200:
          description: "Usuário alterado com sucesso"
        400:
          description: "retorna false para os campos inválidos"
  /users/{id}:
    get:
      tags:
      - "users"
      summary: "Retorna os detalhes do usuário"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Retorna os detalhes do usuário"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                description: "Retorna o ID do usuário autenticado."
              admin:
                type: "boolean"
                description: "Retorna se o usuário é Administrador ou não"
              clientName:
                type: "string"
                description: "Retorna um nome de cliente para o usuário se aplicá\
                  vel"
              clientSecret:
                type: "string"
                description: "Retorna um segredo para autenticar o cliente"
        400:
          description: "Este usuário não existe"
        403:
          description: "Você não tem permissão para isso"
    delete:
      tags:
      - "users"
      summary: "Deleta um usuário pelo id"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Usuário excluído com sucesso"
        403:
          description: "Acesso negado: usuário não possui privilégios de administrador"
        404:
          description: "Este usuário não existe"
  /cliente:
    get:
      tags:
      - "cliente"
      summary: "Verifica se um client existe baseado em seu ID, segredo"
      parameters:
      - name: "clientid"
        in: "header"
        required: true
        type: "string"
      - name: "clientsecret"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: "ok"
        401:
          description: "credenciais_invalidas"
        403:
          description: "cliente_bloqueado"
    post:
      tags:
      - "cliente"
      summary: "Cria um novo cliente"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "cliente atualizado"
          schema:
            type: "object"
            properties:
              nome:
                type: "string"
                description: "nome completo do usuário"
              id:
                type: "string"
                description: "id do usuário"
        201:
          description: "criado novo cliente"
          schema:
            type: "object"
            properties:
              nome:
                type: "string"
                description: "nome completo do usuário"
              id:
                type: "string"
                description: "id do usuario"
        400:
          description: "falha_ao_criar_cliente"
        403:
          description: "cliente bloqueado"
        409:
          description: "cliente_existente"
  /cliente/{id}:
    delete:
      tags:
      - "cliente"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "Cliente excluído com sucesso"
        403:
          description: "Você não tem permissão para isso"
        404:
          description: "Cliente não encontrado"
  /diario:
    get:
      tags:
      - "diários"
      summary: "Retorna todos os diários dado um id de usuário"
      parameters:
      - name: "userid"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: "Retorna lista de diários para um dado usuário"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                description: "ID do livro diário."
              diarioUID:
                type: "string"
                description: "Retorna um ID codificado e único para o livro diário"
              diarioNome:
                type: "string"
                description: "Nome do livro diário"
              diarioDescription:
                type: "string"
                description: "Breve descrição do livro diário"
              isDefault:
                type: "boolean"
                description: "Se o diário é o padrão."
              userid:
                type: "integer"
                description: "ID do usuário dono deste diário"
        400:
          description: "Faltando userid"
        403:
          description: "Não autorizado"
    post:
      tags:
      - "diários"
      summary: "Cria um novo diário e retorna seu uid"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body"
      responses:
        201:
          description: "criado"
          schema:
            type: "object"
            properties:
              uid:
                type: "string"
                description: "Unique ID do diário criado"
        400:
          description: "sintaxe de entrada inválida"
  /diario/{diariouid}:
    get:
      tags:
      - "diários"
      summary: "Cria um novo diário e retorna seu uid"
      parameters:
      - name: "diariouid"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Retorna um diário para um diario UID"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                description: "ID do livro diário."
              diarioUID:
                type: "string"
                description: "Retorna um ID codificado e único para o livro diário"
              diarioNome:
                type: "string"
                description: "Nome do livro diário"
              diarioDescription:
                type: "string"
                description: "Breve descrição do livro diário"
              isDefault:
                type: "boolean"
                description: "Se o diário é o padrão."
              userid:
                type: "integer"
                description: "ID do usuário dono deste diário"
        403:
          description: "Não autorizado"
        404:
          description: "Não encontrado"
  /diario/put:
    post:
      tags:
      - "diários"
      summary: "Atualiza um diário dado seu uid"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_1"
      responses:
        200:
          description: "ok"
        400:
          description: "sintaxe de entrada inválida"
  /diario/delete:
    post:
      tags:
      - "diários"
      summary: "apaga um diário dado seu uid"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_2"
      responses:
        200:
          description: "deletado"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado para deletar"
  /diario/select:
    post:
      tags:
      - "diários"
      summary: "seleciona e torna o diário do usuário como padrão"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_3"
      responses:
        200:
          description: "selecionado"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /categoria/{diariouid}:
    get:
      tags:
      - "categorias"
      summary: "retorna todas as categorias dado um diario"
      parameters:
      - name: "diariouid"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "array com as categorias e subcategorias do diaroi"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                categoria_id:
                  type: "integer"
                  description: "ID interno da categoria"
                categoria_nome:
                  type: "string"
                  description: "Nome da categoria"
                categoria_description:
                  type: "string"
                  description: "Descrição da categoria"
                diario_id:
                  type: "integer"
                  description: "Id do diário mãe"
                categoria_ordem:
                  type: "integer"
                  description: "Ordem da categoria"
                subcategorias:
                  type: "array"
                  items:
                    $ref: "#/definitions/categoriadiariouid_subcategorias"
        400:
          description: "sintaxe de entrada inválida"
        403:
          description: "não autorizado"
  /categoria_tabular/{diariouid}:
    get:
      tags:
      - "categorias"
      summary: "retorna todas as categorias dado um diario"
      parameters:
      - name: "diariouid"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "array com as categorias e subcategorias do diaroi"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                categoria_id:
                  type: "integer"
                  description: "ID interno da categoria"
                categoria_nome:
                  type: "string"
                  description: "Nome da categoria"
                categoria_description:
                  type: "string"
                  description: "Descrição da categoria"
                diario_id:
                  type: "integer"
                  description: "Id do diário mãe"
                categoria_ordem:
                  type: "integer"
                  description: "Ordem da categoria"
                subcategoria_id:
                  type: "integer"
                  description: "ID interno da subcategoria"
                subcategoria_nome:
                  type: "string"
                  description: "Nome da subcategoria"
                subcategoria_description:
                  type: "string"
                  description: "Descricação da subcategoria"
                subcategoria_carry:
                  type: "integer"
                  description: "Flag que sinaliza se a categoria carrega ou não valores\
                    \ negativos ao próximo mês"
                subcategoria_ordem:
                  type: "integer"
        400:
          description: "sintaxe de entrada inválida"
        403:
          description: "não autorizado"
  /categoria:
    post:
      tags:
      - "categorias"
      summary: "Adiciona ou altera uma categoria"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_4"
      responses:
        200:
          description: "Alterado"
        201:
          description: "Criada"
        400:
          description: "Erro de sintaxe"
        403:
          description: "Sem autorização para isso"
        404:
          description: "Não encontrada para alterar"
  /categoria/delete:
    post:
      tags:
      - "categorias"
      summary: "Deleta uma categoria"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_5"
      responses:
        200:
          description: "Excluido"
        400:
          description: "Erro de sintaxe"
        403:
          description: "Sem autorização para isso"
        404:
          description: "Não encontrada para excluir"
  /subcategoria:
    post:
      tags:
      - "categorias"
      summary: "Adiciona ou altera uma subcategoria"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_6"
      responses:
        200:
          description: "Alterado"
        201:
          description: "Criada"
        400:
          description: "Erro de sintaxe"
        403:
          description: "Sem autorização para isso"
        404:
          description: "Não encontrada para alterar"
  /subcategoria/delete:
    post:
      tags:
      - "categorias"
      summary: "Deleta uma subcategoria"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_7"
      responses:
        200:
          description: "Excluido"
        400:
          description: "Erro de sintaxe"
        403:
          description: "Sem autorização para isso"
        404:
          description: "Não encontrada para excluir"
  /categoria/move:
    post:
      tags:
      - "categorias"
      summary: "Muda a ordem de uma categoria"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_8"
      responses:
        200:
          description: "reordenado"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /subcategoria/move:
    post:
      tags:
      - "categorias"
      summary: "Muda a ordem de uma subcategoria"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_9"
      responses:
        200:
          description: "reordenado"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /transacao:
    get:
      tags:
      - "transações"
      summary: "Lista todas as transações dado um diario_uid e filtros"
      parameters:
      - name: "diariouid"
        in: "header"
        required: true
        type: "string"
      - name: "filtros"
        in: "header"
        required: false
        type: "string"
      responses:
        200:
          description: "array com as transacoes e subtransacoes"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                transacao_id:
                  type: "integer"
                  description: "ID interno da transacao"
                transacao_nome:
                  type: "string"
                  description: "Nome da transacao"
                transacao_data:
                  type: "string"
                  description: "Data da transacao"
                transacao_sacado:
                  type: "string"
                  description: "Sacado da transacao"
                transacao_descricao:
                  type: "string"
                  description: "Descricao da transacao"
                transacao_valor:
                  type: "number"
                  description: "Valor da transação"
                transacao_conciliada:
                  type: "boolean"
                  description: "Se a transação foi conciliada"
                transacao_aprovada:
                  type: "boolean"
                  description: "Se a transação já foi aprovada"
                transacao_merged_to_id:
                  type: "integer"
                  description: "Caso a transação tenha sido mesclada com outra, o\
                    \ id desta"
                conta_id:
                  type: "integer"
                  description: "O id da conta a qual esta transação pertence"
                conta_nome:
                  type: "string"
                  description: "O nome da conta a qual esta transação pertence"
                diario_uid:
                  type: "string"
                  description: "O UID do diario a qual esta transação pertence"
                subtransacoes:
                  type: "array"
                  items:
                    $ref: "#/definitions/transacao_subtransacoes"
        400:
          description: "sintaxe de entrada inválida"
        403:
          description: "não autorizado"
    post:
      tags:
      - "transações"
      summary: "Cria ou altera uma transação"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_10"
      responses:
        200:
          description: "ok"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                transacao_id:
                  type: "integer"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /transacao/delete:
    post:
      tags:
      - "transações"
      summary: "Deleta uma ou mais transações"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_11"
      responses:
        200:
          description: "ok"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /transacao/aprova:
    post:
      tags:
      - "transações"
      summary: "Aprova ou reprova uma ou mais transações"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/body_12"
      responses:
        200:
          description: "ok"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /transacao/concilia:
    post:
      tags:
      - "transações"
      summary: "Concilia ou não uma ou mais transações"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/body_13"
      responses:
        200:
          description: "ok"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /subtransacao:
    post:
      tags:
      - "transações"
      summary: "Cria ou altera uma subtransação"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_14"
      responses:
        200:
          description: "ok"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                transacao_id:
                  type: "integer"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /subtransacao/delete:
    post:
      tags:
      - "transações"
      summary: "Deleta uma ou mais subtransações"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_15"
      responses:
        200:
          description: "ok"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /subtransacao/aprova:
    post:
      tags:
      - "transações"
      summary: "Aprova ou reprova uma ou mais subtransações"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/body_12"
      responses:
        200:
          description: "ok"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /subtransacao/concilia:
    post:
      tags:
      - "transações"
      summary: "Concilia ou não uma ou mais subtransações"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/body_13"
      responses:
        200:
          description: "ok"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /orcamento:
    get:
      tags:
      - "orçamentos"
      summary: "Lista todos os orçamentos para um mesano e um diario_uid"
      parameters:
      - name: "diariouid"
        in: "header"
        required: true
        type: "string"
      - name: "ano"
        in: "header"
        required: true
        type: "string"
      - name: "mes"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: "ok"
          schema:
            type: "object"
            properties:
              orcamento_mesano:
                type: "string"
              orcamento_fundos_mes:
                type: "number"
              orcamento_sobregasto_mes_anterior:
                type: "number"
              orcamento_orcado_mes:
                type: "number"
              orcamento_fundo_disponivel_mes:
                type: "number"
              categorias:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_8_categorias"
        400:
          description: "sintaxe inválida"
        403:
          description: "não autorizado"
        404:
          description: "não encontrado"
  /contas/{diariouid}:
    get:
      tags:
      - "contas"
      summary: "Lista todas as contas para um diario_uid"
      parameters:
      - name: "diariouid"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "ok"
          schema:
            type: "object"
            properties:
              conta_id:
                type: "number"
              conta_nome:
                type: "string"
              conta_descricao:
                type: "string"
              conta_reconciliado_valor:
                type: "number"
              conta_reconciliado_data:
                type: "string"
              conta_budget:
                type: "boolean"
              conta_cartao:
                type: "boolean"
              conta_cartao_data_vencimento:
                type: "string"
              conta_cartao_data_fechamento:
                type: "string"
              bank_id:
                type: "number"
              conta_img:
                type: "string"
  /conta:
    post:
      tags:
      - "contas"
      summary: "Adiciona ou altera uma conta"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body_16"
      responses:
        200:
          description: "ok"
          schema:
            type: "object"
            properties:
              conta_id:
                type: "number"
  /conta/delete/{conta_id}:
    post:
      tags:
      - "contas"
      summary: "Deleta uma conta"
      parameters:
      - name: "conta_id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "ok"
        403:
          description: "sem privilégios para isso"
        404:
          description: "conta não encontrada"
securityDefinitions:
  autenticar:
    type: "oauth2"
    tokenUrl: "https://api.rafacla.com/auth"
    flow: "password"
    scopes:
      user: "Atividades de um usuário comum"
      adm: "Atividades de um administrador"
  application:
    type: "oauth2"
    tokenUrl: "https://api.rafacla.com/auth"
    flow: "application"
    scopes:
      user: "Atividades de um usuário comum"
      adm: "Atividades de um administrador"
definitions:
  User:
    type: "object"
    required:
    - "userEmail"
    - "userFirstName"
    - "userLastName"
    - "userPassword"
    - "userPhoneNumber"
    properties:
      userID:
        type: "integer"
        format: "int64"
      userEmail:
        type: "string"
      userPassword:
        type: "string"
      userFirstName:
        type: "string"
      userLastName:
        type: "string"
      userPhoneNumber:
        type: "string"
      userActive:
        type: "boolean"
      userNotActiveReason:
        type: "string"
      inputIP:
        type: "string"
        description: "For 'web' client, consider this inputIP"
    xml:
      name: "User"
    example:
      userActive: true
      userNotActiveReason: "userNotActiveReason"
      userPassword: "userPassword"
      inputIP: "inputIP"
      userLastName: "userLastName"
      userPhoneNumber: "userPhoneNumber"
      userEmail: "userEmail"
      userFirstName: "userFirstName"
      userID: 0
  Cliente:
    type: "object"
    properties:
      client_id:
        type: "string"
        maxLength: 80
      client_secret:
        type: "string"
        maxLength: 80
      user_id:
        type: "integer"
      description:
        type: "string"
    xml:
      name: "Cliente"
    example:
      user_id: 0
      description: "description"
      client_secret: "client_secret"
      client_id: "client_id"
  inline_response_200:
    properties:
      userID:
        type: "number"
      userEmail:
        type: "string"
      userPassword:
        type: "string"
      userFirstName:
        type: "string"
      userLastName:
        type: "string"
      userPhoneNumber:
        type: "string"
      userLastLoginIP:
        type: "string"
      userLastLoginDate:
        type: "string"
      userActivationCode:
        type: "string"
      userForgottenPasswordCode:
        type: "string"
      userForgottenPasswordTime:
        type: "string"
      userActive:
        type: "boolean"
      userNotActiveReason:
        type: "string"
    example:
      userNotActiveReason: "userNotActiveReason"
      userPassword: "userPassword"
      userPhoneNumber: "userPhoneNumber"
      userForgottenPasswordCode: "userForgottenPasswordCode"
      userFirstName: "userFirstName"
      userID: 0.80082819046101150206595775671303272247314453125
      userLastLoginDate: "userLastLoginDate"
      userForgottenPasswordTime: "userForgottenPasswordTime"
      userActive: true
      userActivationCode: "userActivationCode"
      userLastName: "userLastName"
      userEmail: "userEmail"
      userLastLoginIP: "userLastLoginIP"
  inline_response_201:
    properties:
      id:
        type: "integer"
        description: "Retorna o ID do novo usuário."
    example:
      id: 0
  inline_response_400:
    properties:
      username:
        type: "boolean"
      firstName:
        type: "boolean"
      lastName:
        type: "boolean"
      email:
        type: "boolean"
      password:
        type: "boolean"
      phoneNumber:
        type: "boolean"
  inline_response_201_1:
    properties:
      status:
        type: "boolean"
        description: "Retorna true se for sucesso"
      id:
        type: "integer"
        description: "Retorna o ID do novo usuário."
    example:
      id: 0
      status: true
  inline_response_400_1:
    properties:
      status:
        type: "boolean"
        example: false
        description: "retorna false se falhar"
      reason:
        type: "string"
        example: "usuario_existente"
        description: "retorna usuario_existente ou erro_desconhecido"
  inline_response_200_1:
    properties:
      id:
        type: "integer"
        description: "Retorna o ID do usuário autenticado."
      admin:
        type: "boolean"
        description: "Retorna se o usuário é Administrador ou não"
      clientName:
        type: "string"
        description: "Retorna um nome de cliente para o usuário se aplicável"
      clientSecret:
        type: "string"
        description: "Retorna um segredo para autenticar o cliente"
    example:
      clientName: "clientName"
      admin: true
      clientSecret: "clientSecret"
      id: 0
  inline_response_200_2:
    properties:
      nome:
        type: "string"
        description: "nome completo do usuário"
      id:
        type: "string"
        description: "id do usuário"
    example:
      nome: "nome"
      id: "id"
  inline_response_201_2:
    properties:
      nome:
        type: "string"
        description: "nome completo do usuário"
      id:
        type: "string"
        description: "id do usuario"
  inline_response_200_3:
    properties:
      id:
        type: "integer"
        description: "ID do livro diário."
      diarioUID:
        type: "string"
        description: "Retorna um ID codificado e único para o livro diário"
      diarioNome:
        type: "string"
        description: "Nome do livro diário"
      diarioDescription:
        type: "string"
        description: "Breve descrição do livro diário"
      isDefault:
        type: "boolean"
        description: "Se o diário é o padrão."
      userid:
        type: "integer"
        description: "ID do usuário dono deste diário"
    example:
      isDefault: true
      diarioUID: "diarioUID"
      diarioDescription: "diarioDescription"
      id: 0
      diarioNome: "diarioNome"
      userid: 6
  body:
    type: "object"
    properties:
      nome:
        type: "string"
      description:
        type: "string"
      userid:
        type: "integer"
  inline_response_201_3:
    properties:
      uid:
        type: "string"
        description: "Unique ID do diário criado"
    example:
      uid: "uid"
  body_1:
    type: "object"
    properties:
      uniqueid:
        type: "string"
      nome:
        type: "string"
      description:
        type: "string"
  body_2:
    type: "object"
    properties:
      uniqueid:
        type: "string"
  body_3:
    type: "object"
    properties:
      uniqueid:
        type: "string"
  categoriadiariouid_subcategorias:
    properties:
      subcategoria_id:
        type: "integer"
        description: "ID interno da subcategoria"
      subcategoria_nome:
        type: "string"
        description: "Nome da subcategoria"
      subcategoria_description:
        type: "string"
        description: "Descricação da subcategoria"
      subcategoria_carry:
        type: "integer"
        description: "Flag que sinaliza se a categoria carrega ou não valores negativos\
          \ ao próximo mês"
      categoria_id:
        type: "integer"
        description: "id da categoria mãe"
  inline_response_200_4:
    properties:
      categoria_id:
        type: "integer"
        description: "ID interno da categoria"
      categoria_nome:
        type: "string"
        description: "Nome da categoria"
      categoria_description:
        type: "string"
        description: "Descrição da categoria"
      diario_id:
        type: "integer"
        description: "Id do diário mãe"
      categoria_ordem:
        type: "integer"
        description: "Ordem da categoria"
      subcategorias:
        type: "array"
        items:
          $ref: "#/definitions/categoriadiariouid_subcategorias"
  inline_response_200_5:
    properties:
      categoria_id:
        type: "integer"
        description: "ID interno da categoria"
      categoria_nome:
        type: "string"
        description: "Nome da categoria"
      categoria_description:
        type: "string"
        description: "Descrição da categoria"
      diario_id:
        type: "integer"
        description: "Id do diário mãe"
      categoria_ordem:
        type: "integer"
        description: "Ordem da categoria"
      subcategoria_id:
        type: "integer"
        description: "ID interno da subcategoria"
      subcategoria_nome:
        type: "string"
        description: "Nome da subcategoria"
      subcategoria_description:
        type: "string"
        description: "Descricação da subcategoria"
      subcategoria_carry:
        type: "integer"
        description: "Flag que sinaliza se a categoria carrega ou não valores negativos\
          \ ao próximo mês"
      subcategoria_ordem:
        type: "integer"
  body_4:
    type: "object"
    properties:
      categoria_id:
        type: "integer"
        description: "enviar o código da categoria caso seja edição, não enviar nada\
          \ se for inclusão"
      categoria_nome:
        type: "string"
      categoria_description:
        type: "string"
      categoria_ordem:
        type: "integer"
      diario_uid:
        type: "string"
  body_5:
    type: "object"
    properties:
      categoria_id:
        type: "integer"
  body_6:
    type: "object"
    properties:
      subcategoria_id:
        type: "integer"
        description: "enviar o código da subcategoria caso seja edição, não enviar\
          \ nada se for inclusão"
      subcategoria_nome:
        type: "string"
      subcategoria_description:
        type: "string"
      subcategoria_ordem:
        type: "integer"
      subcategoria_carry:
        type: "integer"
      categoria_id:
        type: "integer"
  body_7:
    type: "object"
    properties:
      subcategoria_id:
        type: "integer"
  body_8:
    type: "object"
    properties:
      categoria_id:
        type: "integer"
      move_to:
        type: "integer"
  body_9:
    type: "object"
    properties:
      subcategoria_id:
        type: "integer"
      move_to:
        type: "integer"
      move_to_categoria_id:
        type: "integer"
  transacao_subtransacoes:
    properties:
      subtransacao_id:
        type: "integer"
        description: "ID interno da subtransacao"
      subtransacao_nome:
        type: "string"
        description: "Nome da subtransacao"
      subtransacao_description:
        type: "string"
        description: "Descricação da subtransacao"
      categoria_id:
        type: "integer"
        description: "ID da categoria atribuída a esta transação"
      categoria_nome:
        type: "string"
        description: "Nome da categoria atribuída a esta transação"
      subcategoria_id:
        type: "integer"
        description: "ID da subcategoria atribuída a esta transação"
      subcategoria_nome:
        type: "string"
        description: "Nome da subcategoria atribuída a esta transação"
      transf_para_conta_id:
        type: "integer"
        description: "ID da conta se esta subtransação for uma transferência"
  inline_response_200_6:
    properties:
      transacao_id:
        type: "integer"
        description: "ID interno da transacao"
      transacao_nome:
        type: "string"
        description: "Nome da transacao"
      transacao_data:
        type: "string"
        description: "Data da transacao"
      transacao_sacado:
        type: "string"
        description: "Sacado da transacao"
      transacao_descricao:
        type: "string"
        description: "Descricao da transacao"
      transacao_valor:
        type: "number"
        description: "Valor da transação"
      transacao_conciliada:
        type: "boolean"
        description: "Se a transação foi conciliada"
      transacao_aprovada:
        type: "boolean"
        description: "Se a transação já foi aprovada"
      transacao_merged_to_id:
        type: "integer"
        description: "Caso a transação tenha sido mesclada com outra, o id desta"
      conta_id:
        type: "integer"
        description: "O id da conta a qual esta transação pertence"
      conta_nome:
        type: "string"
        description: "O nome da conta a qual esta transação pertence"
      diario_uid:
        type: "string"
        description: "O UID do diario a qual esta transação pertence"
      subtransacoes:
        type: "array"
        items:
          $ref: "#/definitions/transacao_subtransacoes"
  body_10:
    type: "object"
    properties:
      diario_uid:
        type: "string"
      transacao_id:
        type: "integer"
      transacao_numero:
        type: "string"
      transacao_data:
        type: "string"
      transacao_sacado:
        type: "string"
      transacao_descricao:
        type: "string"
      transacao_valor:
        type: "number"
      transacao_conciliada:
        type: "boolean"
      transacao_aprovada:
        type: "boolean"
      transacao_merged_to_id:
        type: "integer"
      conta_id:
        type: "integer"
  inline_response_200_7:
    properties:
      transacao_id:
        type: "integer"
  body_11:
    type: "object"
    properties:
      transacao_id:
        type: "array"
        items:
          type: "integer"
  body_12:
    properties:
      id:
        type: "integer"
      aprova:
        type: "boolean"
  body_13:
    properties:
      id:
        type: "integer"
      concilia:
        type: "boolean"
  body_14:
    type: "object"
    properties:
      subtransacao_id:
        type: "integer"
      transacao_id:
        type: "integer"
      subtransacao_valor:
        type: "number"
      subtransacao_descricao:
        type: "string"
      subcategoria_id:
        type: "integer"
      transf_para_conta_id:
        type: "integer"
        description: "se preenchido, a subtransacao passa a ser tratada como transferê\
          ncia e a subcategoria_id é ignorada"
  body_15:
    type: "object"
    properties:
      transacao_id:
        type: "array"
        items:
          type: "integer"
  inline_response_200_8_subcategorias:
    properties:
      subcategoria_id:
        type: "integer"
      subcategoria_nome:
        type: "string"
      subcategoria_orcado:
        type: "number"
      subcategoria_incorrido:
        type: "number"
      subcategoria_disponivel:
        type: "number"
      subcategoria_persiste_negativo:
        type: "boolean"
    example:
      subcategoria_persiste_negativo: true
      subcategoria_id: 3
      subcategoria_disponivel: 7.3862819483858839220147274318151175975799560546875
      subcategoria_incorrido: 4.1456080298839363962315474054776132106781005859375
      subcategoria_nome: "subcategoria_nome"
      subcategoria_orcado: 2.027123023002321833274663731572218239307403564453125
  inline_response_200_8_categorias:
    properties:
      categoria_id:
        type: "integer"
      categoria_nome:
        type: "string"
      categoria_orcado:
        type: "number"
      categoria_incorrido:
        type: "number"
      categoria_disponivel:
        type: "number"
      subcategorias:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_8_subcategorias"
    example:
      categoria_nome: "categoria_nome"
      subcategorias:
      - subcategoria_persiste_negativo: true
        subcategoria_id: 3
        subcategoria_disponivel: 7.3862819483858839220147274318151175975799560546875
        subcategoria_incorrido: 4.1456080298839363962315474054776132106781005859375
        subcategoria_nome: "subcategoria_nome"
        subcategoria_orcado: 2.027123023002321833274663731572218239307403564453125
      - subcategoria_persiste_negativo: true
        subcategoria_id: 3
        subcategoria_disponivel: 7.3862819483858839220147274318151175975799560546875
        subcategoria_incorrido: 4.1456080298839363962315474054776132106781005859375
        subcategoria_nome: "subcategoria_nome"
        subcategoria_orcado: 2.027123023002321833274663731572218239307403564453125
      categoria_disponivel: 9.301444243932575517419536481611430644989013671875
      categoria_incorrido: 7.061401241503109105224211816675961017608642578125
      categoria_id: 5
      categoria_orcado: 2.3021358869347654518833223846741020679473876953125
  inline_response_200_8:
    properties:
      orcamento_mesano:
        type: "string"
      orcamento_fundos_mes:
        type: "number"
      orcamento_sobregasto_mes_anterior:
        type: "number"
      orcamento_orcado_mes:
        type: "number"
      orcamento_fundo_disponivel_mes:
        type: "number"
      categorias:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_8_categorias"
    example:
      orcamento_fundos_mes: 0.80082819046101150206595775671303272247314453125
      orcamento_mesano: "orcamento_mesano"
      categorias:
      - categoria_nome: "categoria_nome"
        subcategorias:
        - subcategoria_persiste_negativo: true
          subcategoria_id: 3
          subcategoria_disponivel: 7.3862819483858839220147274318151175975799560546875
          subcategoria_incorrido: 4.1456080298839363962315474054776132106781005859375
          subcategoria_nome: "subcategoria_nome"
          subcategoria_orcado: 2.027123023002321833274663731572218239307403564453125
        - subcategoria_persiste_negativo: true
          subcategoria_id: 3
          subcategoria_disponivel: 7.3862819483858839220147274318151175975799560546875
          subcategoria_incorrido: 4.1456080298839363962315474054776132106781005859375
          subcategoria_nome: "subcategoria_nome"
          subcategoria_orcado: 2.027123023002321833274663731572218239307403564453125
        categoria_disponivel: 9.301444243932575517419536481611430644989013671875
        categoria_incorrido: 7.061401241503109105224211816675961017608642578125
        categoria_id: 5
        categoria_orcado: 2.3021358869347654518833223846741020679473876953125
      - categoria_nome: "categoria_nome"
        subcategorias:
        - subcategoria_persiste_negativo: true
          subcategoria_id: 3
          subcategoria_disponivel: 7.3862819483858839220147274318151175975799560546875
          subcategoria_incorrido: 4.1456080298839363962315474054776132106781005859375
          subcategoria_nome: "subcategoria_nome"
          subcategoria_orcado: 2.027123023002321833274663731572218239307403564453125
        - subcategoria_persiste_negativo: true
          subcategoria_id: 3
          subcategoria_disponivel: 7.3862819483858839220147274318151175975799560546875
          subcategoria_incorrido: 4.1456080298839363962315474054776132106781005859375
          subcategoria_nome: "subcategoria_nome"
          subcategoria_orcado: 2.027123023002321833274663731572218239307403564453125
        categoria_disponivel: 9.301444243932575517419536481611430644989013671875
        categoria_incorrido: 7.061401241503109105224211816675961017608642578125
        categoria_id: 5
        categoria_orcado: 2.3021358869347654518833223846741020679473876953125
      orcamento_orcado_mes: 1.46581298050294517310021547018550336360931396484375
      orcamento_sobregasto_mes_anterior: 6.02745618307040320615897144307382404804229736328125
      orcamento_fundo_disponivel_mes: 5.962133916683182377482808078639209270477294921875
  inline_response_200_9:
    properties:
      conta_id:
        type: "number"
      conta_nome:
        type: "string"
      conta_descricao:
        type: "string"
      conta_reconciliado_valor:
        type: "number"
      conta_reconciliado_data:
        type: "string"
      conta_budget:
        type: "boolean"
      conta_cartao:
        type: "boolean"
      conta_cartao_data_vencimento:
        type: "string"
      conta_cartao_data_fechamento:
        type: "string"
      bank_id:
        type: "number"
      conta_img:
        type: "string"
    example:
      conta_reconciliado_data: "conta_reconciliado_data"
      conta_nome: "conta_nome"
      conta_cartao: true
      conta_id: 0.80082819046101150206595775671303272247314453125
      conta_descricao: "conta_descricao"
      bank_id: 1.46581298050294517310021547018550336360931396484375
      conta_cartao_data_fechamento: "conta_cartao_data_fechamento"
      conta_reconciliado_valor: 6.02745618307040320615897144307382404804229736328125
      conta_cartao_data_vencimento: "conta_cartao_data_vencimento"
      conta_budget: true
      conta_img: "conta_img"
  body_16:
    type: "object"
    properties:
      conta_id:
        type: "integer"
        description: "enviar o código da conta caso seja edição, não enviar nada se\
          \ for inclusão"
      conta_nome:
        type: "string"
      conta_descricao:
        type: "string"
      conta_budget:
        type: "boolean"
      diario_uid:
        type: "string"
      conta_reconciliado_valor:
        type: "number"
      conta_reconciliado_data:
        type: "string"
      conta_cartao:
        type: "boolean"
      conta_cartao_data_fechamento:
        type: "string"
      conta_cartao_data_vencimento:
        type: "string"
      bank_id:
        type: "number"
      conta_img:
        type: "string"
  inline_response_200_10:
    properties:
      conta_id:
        type: "number"
    example:
      conta_id: 0.80082819046101150206595775671303272247314453125
